config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

 
match "/candidates/select_dist", :to => "candidates#select_dist", :via => ["post","get"]
match "/candidates/party_candidate", :to => "candidates#party_candidate", :via => ["post","get"]
match "/votes/vote_by_user", :to => "votes#vote_by_user", :via => ["post","get"]
match "/candidates/:id", :to => "candidates#index", :via => ["get"]
match "/admins", :to => "admins#index", :via => ["get"]
match "/admins/login", :to => "admins#login", :via => ["post"]
match "/admins/logout", :to => "admins#logout", :via => ["get"]
 resources :votes
  resources :candidates
  resources :areas
  resources :district_lists
  resources :party_lists

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	belongs_to :party_list
	belongs_to :area
	has_many :votes
	has_attached_file :avatar,
                   styles: {
                     medium: '300x300>',
                     thumb: '100x100>'
                   }                    

 validates_attachment_content_type :avatar, content_type: %r{\Aimage\/.*\Z}
 validates_with AttachmentSizeValidator, attributes: :avatar,
                                         less_than: 2.megabytes
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]
before_action :check_admin, only: [:index, :create, :update, :destroy, :edit]
  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all.order(:id)
    #render json: @candidates
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    index
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def select_dist
  @dist = DistrictList.all
  if params[:dist_id]
    @area = DistrictList.find(params[:dist_id]).areas
    render :layout=>false
  end
end

def party_candidate
 
  if params[:party_id]
   @candidates = Candidate.where("party_list_id=#{params[:party_id]}").order(:id)
    render :layout=>false
  end
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:area_id, :party_list_id, :name, :image, :district_list_id, :desc, :avatar, :x1, :x2, :x3, :x4, :x5, :x6, :x7, :x8, :x9, :x10, :x11, :x12, :x13, :x14, :x15,:cm_candidate)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 


 
 <table align="center"> 
<tr>
    <td ><%= f.label :party_list_id %></td>
    <td><%= select("candidate", "party_list_id", PartyList.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Party'},:class=>'select_box_vote')%> </td>
  </tr>

  <tr>
    <td >Select District: </td>
    <td><%= select("candidate", "district_list_id", DistrictList.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select District'},:class=>'select_box_vote', :onchange=>"return select_area(this.value)") %> </td>
  </tr>

<tr id="area_update">
<td >Select Constituency(தொகுதி): </td>
    <td><select class="select_box_vote"> 
      <option value='0'>Select Constituency(தொகுதி)</option>
        </select>

    </td>
</tr>

<tr>
    <td ><%= f.label :name %> </td>
    <td><%= f.text_area :name ,:class=>'select_box_vote'%> </td>
  </tr>
  <tr>
    <td >CM Candidate </td>
    <td>
      <%if @candidate.cm_candidate.to_i==1%>
<input type="checkbox" id="cm_candidate" name="candidate[cm_candidate]" value="1"
      onclick="return cm_candidate_yes(this.value)" checked/>
      <%else%>
         <input type="checkbox" id="cm_candidate" name="candidate[cm_candidate]" value="0"
      onclick="return cm_candidate_yes(this.value)"/>
      <%end%>
       </td>
  </tr>
  <tr>
    <td ><%= f.label :avatar %></td>
    <td><%= f.file_field :avatar %> <%if @edit and @edit.to_i==1%>
      <%if @candidate.avatar.to_s != "/avatars/original/missing.png"%>
      <%= image_tag @candidate.avatar, :size => "70x50", class: "icons"%>
      
      <%end%> 
      <%end%></td>
  </tr>

  <%(1..15).each do |c|
    get_decs_cat_value(c,@candidate)%>
    
  <tr>
  <td >Category <%=c%></td>
    <td><textarea class="select_box_vote" name="candidate[x<%=c%>]" id="candidate_x<%=c%>" 
     ><%=@desc_cat%></textarea> </td>
</tr>
<%end%>


</table>
  <div class="actions" align="center">
    <%if @edit and @edit.to_i==1%>
    <script>
  select_area(<%=@candidate.district_list_id%>)
  setTimeout(function(){ select_candidate_area(<%=@candidate.area_id%>,'area_id') }, 100);  
  </script>
    <%#= f.submit %><input type="submit" name="commit" value="Update Candidate" class="button_blue_submit" style="width:200px;">
    <%else%>
    <input type="submit" name="commit" value="Create Candidate" class="button_blue_submit" style="width:200px;">
    <%end%>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<hr>
<div align="center"><font size="3" color="#FC8507"><b>Editing Candidate</b></font></div><hr>

<a href="/candidates" style="padding-left:30px;"><font style="color:blue;">Back</font></a>
</br>
<%@edit=1%>
<%= render 'form' %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>
<hr>
<div align="center"><font size="3" color="#FC8507"><b>Candidates List</b></font></div><hr>
<%if session[:user] && session[:user]!=""%>
<div align="right"><a href="/admins/logout" style="padding-right:60px;" ><font style="color:blue;">Logout</font></a></div>
<%end%>
<a href="/candidates/new" style="padding-left:30px;"><font style="color:blue;">Add New Candidate</font></a>
<a href="/party_lists" style="padding-left:30px;"><font style="color:blue;">View Party</font></a>
</br>
<table align="center"> 
<tr>
    <td >Select Party</td>
    <td><%= select("candidate", "party_list_id", PartyList.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Party'},:class=>'select_box_vote', :onchange=>"return select_party(this.value)")%> </td>
  </tr>
</table>
</br>
</br>
<div id="update_candiate" align="center">

</div>

<script type="text/javascript">
setTimeout(function(){ select_candidate_area(<%=PartyList.all[0].id%>,'candidate_party_list_id') }, 100);
</script>

<br>

app/views/candidates/new.html.erb
<hr>
<div align="center"><font size="3" color="#FC8507"><b>Add New Candidate</b></font></div><hr>
<a href="/candidates" style="padding-left:15px;"><font style="color:blue;">Back</font></a>
<%= render 'form' %>

app/views/candidates/party_candidate.html.erb
<table border='1px' width="80%" class="table_view">
  <thead>
    <tr class="header_bg"> 
<th>S.No</th>
      <th>Name</th>
           
     <th>District</th> 
     <th>Constituency(தொகுதி)</th>  
      <th>Image</th>  
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <%  i=1
    @candidates.each do |candidate| %>
      <tr class="odd">
        <td width="2%" align="center"><%= i %></td>
        <td width="15%"><%= candidate.name %></td>
              
        <td width="15%"><%if candidate.district_list_id.to_i!=0%><%= DistrictList.find(candidate.district_list_id).name %><%end%></td>
        <td width="15%"><%if candidate.area_id.to_i!=0%><%= Area.find(candidate.area_id).name %><%end%></td>
        <td width="15%" align="center"><%if candidate.avatar.to_s != "/avatars/original/missing.png"%>
<%= image_tag candidate.avatar, :size => "70x50"%>
<%else%>
<img src="/assets/question.jpg" alt="Missing" width="70" height="50">
<%end%></td>        
        <td align="center" width="5%"><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td align="center" width="5%"><%= link_to 'Delete', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% i=i+1
    end %>
  </tbody>
</table>

app/views/candidates/select_dist.html.erb
	<%if params[:dist_id]%>


	
		<td >Select Constituency(தொகுதி): </td>
		<td><select class="select_box_vote" id="area_id" name="candidate[area_id]"> 
			<option value='0'>Select Constituency(தொகுதி)</option>
         <%@area.each do |a|%>
             <option value="<%=a.id%>"><%=a.name%></option>
         <%end%>

		</select>

		</td>

<%else%>
<table align="center"> 

	<tr>
		<td >Select District: </td>
		<td><%= select("area", "district_list_id", @dist.collect {|p| [ p.name, p.id ] }, {prompt: 'Select District'},:class=>'select_box_vote', :onchange=>"return select_area(this.value)") %> </td>
	</tr>
<tr id="area_update">
<td >Select Constituency(தொகுதி): </td>
		<td><select class="select_box_vote"> 
			<option value='0'>Select Constituency(தொகுதி)</option>
        </select>

		</td>
</tr>


</table>

</br>
<div align="center">
 <input type='button' onClick="return submit_area(this);" value='Submit' class="button_blue_submit"/>
</div>
</br>
</br>
<%end%>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @candidate.area_id %>
</p>

<p>
  <strong>Party list:</strong>
  <%= @candidate.party_list_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @candidate.image %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>