config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

 
match "/candidates/select_dist", :to => "candidates#select_dist", :via => ["post","get"]
match "/candidates/party_candidate", :to => "candidates#party_candidate", :via => ["post","get"]
match "/votes/vote_by_user", :to => "votes#vote_by_user", :via => ["post","get"]
match "/candidates/:id", :to => "candidates#index", :via => ["get"]
match "/admins", :to => "admins#index", :via => ["get"]
match "/admins/login", :to => "admins#login", :via => ["post"]
match "/admins/logout", :to => "admins#logout", :via => ["get"]
 resources :votes
  resources :candidates
  resources :areas
  resources :district_lists
  resources :party_lists

end

app/models/district_list.rb
class DistrictList < ActiveRecord::Base
	has_many :areas
end

app/controllers/district_lists_controller.rb
class DistrictListsController < ApplicationController
  before_action :set_district_list, only: [:show, :edit, :update, :destroy]

  # GET /district_lists
  # GET /district_lists.json
  def index
    @district_lists = DistrictList.all
  end

  # GET /district_lists/1
  # GET /district_lists/1.json
  def show
  end

  # GET /district_lists/new
  def new
    @district_list = DistrictList.new
  end

  # GET /district_lists/1/edit
  def edit
  end

  # POST /district_lists
  # POST /district_lists.json
  def create
    @district_list = DistrictList.new(district_list_params)

    respond_to do |format|
      if @district_list.save
        format.html { redirect_to @district_list, notice: 'District list was successfully created.' }
        format.json { render :show, status: :created, location: @district_list }
      else
        format.html { render :new }
        format.json { render json: @district_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /district_lists/1
  # PATCH/PUT /district_lists/1.json
  def update
    respond_to do |format|
      if @district_list.update(district_list_params)
        format.html { redirect_to @district_list, notice: 'District list was successfully updated.' }
        format.json { render :show, status: :ok, location: @district_list }
      else
        format.html { render :edit }
        format.json { render json: @district_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /district_lists/1
  # DELETE /district_lists/1.json
  def destroy
    @district_list.destroy
    respond_to do |format|
      format.html { redirect_to district_lists_url, notice: 'District list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district_list
      @district_list = DistrictList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def district_list_params
      params.require(:district_list).permit(:name)
    end
end

app/helpers/district_lists_helper.rb
module DistrictListsHelper
end

app/views/district_lists/_form.html.erb
<%= form_for(@district_list) do |f| %>
  <% if @district_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@district_list.errors.count, "error") %> prohibited this district_list from being saved:</h2>

      <ul>
      <% @district_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/district_lists/edit.html.erb
<h1>Editing District List</h1>

<%= render 'form' %>

<%= link_to 'Show', @district_list %> |
<%= link_to 'Back', district_lists_path %>

app/views/district_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing District Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @district_lists.each do |district_list| %>
      <tr>
        <td><%= district_list.name %></td>
        <td><%= link_to 'Show', district_list %></td>
        <td><%= link_to 'Edit', edit_district_list_path(district_list) %></td>
        <td><%= link_to 'Destroy', district_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New District list', new_district_list_path %>

app/views/district_lists/new.html.erb
<h1>New District List</h1>

<%= render 'form' %>

<%= link_to 'Back', district_lists_path %>

app/views/district_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @district_list.name %>
</p>

<%= link_to 'Edit', edit_district_list_path(@district_list) %> |
<%= link_to 'Back', district_lists_path %>