config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

 
match "/candidates/select_dist", :to => "candidates#select_dist", :via => ["post","get"]
match "/candidates/party_candidate", :to => "candidates#party_candidate", :via => ["post","get"]
match "/votes/vote_by_user", :to => "votes#vote_by_user", :via => ["post","get"]
match "/candidates/:id", :to => "candidates#index", :via => ["get"]
match "/admins", :to => "admins#index", :via => ["get"]
match "/admins/login", :to => "admins#login", :via => ["post"]
match "/admins/logout", :to => "admins#logout", :via => ["get"]
 resources :votes
  resources :candidates
  resources :areas
  resources :district_lists
  resources :party_lists

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :candidate
	belongs_to :party_list
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
def vote_by_user
  @ip_address = request.remote_ip
  @candidate = Candidate.find(params[:candidate_id])
  @candidate_id = @candidate.id
  @area_id = @candidate.area_id
  @party_id = @candidate.party_list_id

@check_vote =  Vote.where("ip_address='#{@ip_address}' and area_id = #{@area_id}")
@already_vote = 0

if @check_vote!=nil && @check_vote.size.to_i!=0
  @already_vote = 1
else
  @new_vote = Vote.new
  @new_vote.candidate_id = params[:candidate_id]
  @new_vote.party_list_id = @party_id
  @new_vote.area_id =  @area_id
  @new_vote.ip_address = @ip_address
  @new_vote.save

# add leading count 
  @all_party = PartyList.all
  @all_area = Area.all
  @lead_party_hash = Hash.new
  @all_area.each do |a|
  @party_hash = Hash.new
    @all_party.each do |p|
    @vote_lead =  Vote.where("area_id = #{a.id} and party_list_id=#{p.id}")
    @party_hash["#{a.id}_#{p.id}"] = @vote_lead.size
    end#@all_party.each do |p|

  @lead_party = @party_hash.values.max
  @party_id = @party_hash.key(@lead_party)

  if @lead_party!=nil and @lead_party.to_s!="" and @lead_party.to_i!=0 and @party_id!=""
  #puts"=@lead_party=====#{@party_hash}=#{@lead_party}=-#{@lead_party.class}---#{@party_id}="
  @find_party = @party_id.split("_")[1]
  if @lead_party_hash["#{@find_party}"]!="" 
  @lead_party_hash["#{@find_party}"] = @lead_party_hash["#{@find_party}"].to_i+1
  else
  @lead_party_hash["#{@find_party}"] = 1
  end
  end
  end#@all_area.each do |a|

 @all_party.each do |p|
 if @lead_party_hash["#{p.id}"].to_i!=0

  p.leading_count = @lead_party_hash["#{p.id}"]
  p.save!
 end
end#@all_party.each do |p|


# add leading count

end

end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:candidate_id, :ip_address)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :candidate_id %><br>
    <%= f.number_field :candidate_id %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votes</h1>

<table>
  <thead>
    <tr>
      <th>Candidate</th>
      <th>Ip address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.candidate_id %></td>
        <td><%= vote.ip_address %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candidate:</strong>
  <%= @vote.candidate_id %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @vote.ip_address %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>

app/views/votes/vote_by_user.html.erb
<%if @already_vote.to_i == 0%>
<div align="center"><font size="3" color="red"><b>You have successfully Voted. Thanks for Voting !!!<br/></font><font size="3" color="blue">தங்களின் ஓட்டு ஏற்றுக்கொள்ளப்பட்டது. மிக்க நன்றி  !!!</b></div><hr>
<div align="center">
<img src='assets/voted.jpg'></div>
<%else%>
<div align="center"><font size="3" color="red"><b>You have already Voted. Don't put FAKE VOTE !!!<br/></font><font size="3" color="blue">கள்ள ஓட்டு போடாதிங்க !!!</b></div><hr>
<div align="center">
<img src='assets/fake.jpg'></div>
<%end%>